sonar.projectKey=gmarupilla_AgroTerraFlow
sonar.organization=gmarupilla
sonar.projectName=AgroTerraFlow
sonar.host.url=https://sonarcloud.io

sonar.sources=terraflow
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/*.ipynb,**/site/**,**/docs/**
sonar.test.inclusions=tests/**
